/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.InputMismatchException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pmora
 */
public class AddRecord extends javax.swing.JFrame {

    /**
     * Creates new form indiRecord
     */
    
    int TyphoonID,Typhoon_No, ImageID, TyphoonID_Image, signal_no, AreaPeople, Year, SignalNumber, HighestWinds, LowestPressure, Total_Fatal, s=0;
    float AreaGDP, Total_Damage;
    char Area_ID, AreaID;
    String AreaName, AreaCapital, InterName, DateFormed, EnteredPH, LeftPH, DateDissolved, BagyoName, category, ImageName, ImagePath, ImageFile, path = null, fname=null; 
    File f = null;
    private ImageIcon format = null;
    byte[] pimage=null;
    
    public AddRecord() {
        initComponents();
        get_ID();
    }
    DefaultTableModel model;
      
    //add record
 
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void get_ID(){
        
        try{
            Connection con = DBConnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select COUNT(TyphoonID) as TOTAL from typhoon");
            String date = "2000-01-01";
            java.util.Date date2 = new SimpleDateFormat("yyyy-MM-dd").parse(date);
            
            
            while (rs.next()) {

                int id = rs.getInt("TOTAL");
                
                
                typhoonID_lbl.setText(String.valueOf(id+1));
                year.setText("");
                intName.setText("");
                lName.setText("");
                signo.getEditor().getItem().toString();
                signo.getEditor().setItem("1");
                dFormed.setDate(date2);
                entPH.setDate(date2);
                leftPH.setDate(date2);
                dDiss.setDate(date2);
                hWind.setText("");
                lPressure.setText("");
                totfat.setText("");
                totdmg.setText("");
                model = (DefaultTableModel) affected_tbl.getModel();
                model.setRowCount(0);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dFormed = new com.toedter.calendar.JDateChooser();
        dDiss = new com.toedter.calendar.JDateChooser();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        entPH = new com.toedter.calendar.JDateChooser();
        leftPH = new com.toedter.calendar.JDateChooser();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        imageLBL = new javax.swing.JLabel();
        view = new javax.swing.JButton();
        view1 = new javax.swing.JButton();
        intName = new javax.swing.JTextField();
        hWind = new javax.swing.JTextField();
        lPressure = new javax.swing.JTextField();
        totdmg = new javax.swing.JTextField();
        totfat = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        lName = new javax.swing.JTextField();
        typhoonID_lbl = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        affected_tbl = new rojeru_san.complementos.RSTableMetro();
        view2 = new javax.swing.JButton();
        aIDc = new javax.swing.JComboBox<>();
        signo = new javax.swing.JComboBox<>();
        view3 = new javax.swing.JButton();
        imagePath = new javax.swing.JTextField();
        view4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(234, 234, 234));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));
        jPanel1.setForeground(new java.awt.Color(249, 249, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Int'l Name:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 55, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Local Name:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 55, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Signal No:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 81, -1, -1));

        dFormed.setToolTipText("");
        jPanel4.add(dFormed, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 50, 140, 30));
        jPanel4.add(dDiss, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 140, 140, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Left PH Date:");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, -1, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Year:");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 81, -1, -1));
        jPanel4.add(entPH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 80, 140, 30));
        jPanel4.add(leftPH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 110, 140, 30));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Highest Winds:");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 107, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Lowest Pressure:");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 133, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Total Damage:");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 133, -1, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("Total Fatalities:");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 107, -1, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setText("Other Areas Affected:");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 261, -1, 33));

        imageLBL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanel4.add(imageLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 252, 513, 329));

        view.setText("Add");
        view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMouseClicked(evt);
            }
        });
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPanel4.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(1181, 120, 93, 33));

        view1.setText("Add");
        view1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view1ActionPerformed(evt);
            }
        });
        jPanel4.add(view1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1181, 636, 93, 33));
        jPanel4.add(intName, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 55, 179, -1));
        jPanel4.add(hWind, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 107, 179, -1));
        jPanel4.add(lPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 133, 179, -1));
        jPanel4.add(totdmg, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 133, 179, -1));
        jPanel4.add(totfat, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 107, 179, -1));
        jPanel4.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 81, 179, -1));
        jPanel4.add(lName, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 55, 179, -1));

        typhoonID_lbl.setEditable(false);
        typhoonID_lbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typhoonID_lblActionPerformed(evt);
            }
        });
        jPanel4.add(typhoonID_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1099, 11, 50, 33));

        affected_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Typhoon ID", "Area ID"
            }
        ));
        affected_tbl.setColorBackgoundHead(new java.awt.Color(255, 255, 255));
        affected_tbl.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        affected_tbl.setColorBordeHead(new java.awt.Color(204, 204, 204));
        affected_tbl.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        affected_tbl.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        affected_tbl.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        affected_tbl.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        affected_tbl.setColorSelBackgound(new java.awt.Color(0, 0, 0));
        affected_tbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        affected_tbl.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        affected_tbl.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        affected_tbl.setFuenteHead(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        affected_tbl.setGridColor(new java.awt.Color(204, 204, 204));
        affected_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                affected_tblMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(affected_tbl);

        jPanel4.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 300, 215, 239));

        view2.setText("Add");
        view2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view2MouseClicked(evt);
            }
        });
        view2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view2ActionPerformed(evt);
            }
        });
        jPanel4.add(view2, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 339, 93, 33));

        aIDc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TWN", "CHN", "PRK", "KOR", "JPN", "GUM", "FSM", "VNM", "KHM", "RUS", "LAO", "THA", "MNP", "HKG", "MMR", "MYS", "CAN", "IND", "PLW", "MAC", "LKA", "IDN", "BGD", "MHL" }));
        aIDc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                aIDcItemStateChanged(evt);
            }
        });
        jPanel4.add(aIDc, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 300, -1, 33));

        signo.setEditable(true);
        signo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jPanel4.add(signo, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 81, 179, -1));

        view3.setText("Generate new ID");
        view3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view3MouseClicked(evt);
            }
        });
        view3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view3ActionPerformed(evt);
            }
        });
        jPanel4.add(view3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1159, 11, -1, 33));

        imagePath.setText("File Name");
        jPanel4.add(imagePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 592, 350, 33));

        view4.setText("Browse");
        view4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view4ActionPerformed(evt);
            }
        });
        jPanel4.add(view4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1181, 592, 93, 33));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Step 1: Create new typhoon record");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Step 2: Add Affected Areas ");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, 27));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Step 3: Add Meteorological History Image");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, 27));

        jLabel21.setText("(NOTE: Put N/A if typhoon names are none)");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, 30));

        jLabel22.setText("(NOTE: Leave blank if none)");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 230, -1, 30));

        jLabel23.setText("(NOTE: Leave blank if none)");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 210, -1, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Typhoon ID:");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, -1, 30));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Date Dissolved:");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 140, -1, 30));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Entered PH Date:");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 80, -1, 30));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Date Formed:");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, -1, 30));

        jPanel3.setBackground(new java.awt.Color(203, 203, 203));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("View Data");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 56, 117, 31));

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Record Viewing");
        jPanel11.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 232, 37));

        jPanel14.setBackground(new java.awt.Color(203, 203, 203));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setText("Manage Records");
        jPanel14.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        jPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 232, 37));

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("Add Records");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 232, 37));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Overview");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 93, 232, 37));

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setText("Create Areas");
        jPanel13.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        jPanel3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 232, 37));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 680));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1310, 680));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Typhoon Database System");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("iPhoon");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 1310, 730));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/im_project/lights.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 7, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/im_project/redo.png"))); // NOI18N
        jLabel10.setToolTipText("");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 0, -1, 28));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/im_project/mini logo.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/im_project/back.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 0, -1, 28));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/im_project/User-Interface-Delete-Sign-icon.png"))); // NOI18N
        close.setToolTipText("");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 0, -1, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseClicked
        if(year.getText().isEmpty() || intName.getText().isEmpty() || lName.getText().isEmpty() || signo.getSelectedItem().toString().isEmpty() || dFormed.toString().isEmpty() || 
                entPH.toString().isEmpty() || leftPH.toString().isEmpty() || dDiss.toString().isEmpty() || hWind.getText().isEmpty() ||
                lPressure.getText().isEmpty() || totfat.getText().isEmpty() || totdmg.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing Fields!");
        }
        else{
        try {
            Connection con = DBConnection.getConnection();
            try {
                Statement dup = con.createStatement();
            String selectQuery = "SELECT * FROM typhoon WHERE TyphoonID="+typhoonID_lbl.getText()+"";
            System.out.println(selectQuery);
            ResultSet rs = dup.executeQuery(selectQuery);
            if (rs.next()==true){
                JOptionPane.showMessageDialog(this, "Typhoon ID "+typhoonID_lbl.getText()+" already exists!");
            }else{
            
            Statement st = con.createStatement();
            PreparedStatement add = con.prepareStatement("insert into typhoon values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
            SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd");
                add.setInt(1, Integer.valueOf(typhoonID_lbl.getText()));
                add.setInt(2, Integer.valueOf(year.getText()));
                add.setString(3, intName.getText());
                add.setString(4, lName.getText());
                add.setInt(5, Integer.valueOf(signo.getSelectedItem().toString()));
                add.setString(6, (Date_Format.format(dFormed.getDate())));
                add.setString(7, (Date_Format.format(entPH.getDate())));
                add.setString(8, (Date_Format.format(leftPH.getDate())));
                add.setString(9, (Date_Format.format(dDiss.getDate())));
                add.setInt(10, Integer.valueOf(hWind.getText()));
                add.setInt(11, Integer.valueOf(lPressure.getText()));
                add.setInt(12, Integer.valueOf(totfat.getText()));
                add.setInt(13, Integer.valueOf(totdmg.getText()));
               
                int row = add.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Typhoon "+typhoonID_lbl.getText()+" Successfully added! "+"\nYou can now add affected areas");
            }
            }catch (NumberFormatException  ex){
                JOptionPane.showMessageDialog(this, "Invalid Input Type!");
            }
            
        } catch (Exception e) {
            e.printStackTrace();

        }
        
        }

        
    }//GEN-LAST:event_viewMouseClicked

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewActionPerformed

    private void affected_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_affected_tblMouseClicked
        
    }//GEN-LAST:event_affected_tblMouseClicked

    private void view2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view2MouseClicked

        try {
            Connection con = DBConnection.getConnection();
            Statement st2 = con.createStatement();
            PreparedStatement add = con.prepareStatement("insert into affected values(?,?)");
                add.setInt(1, Integer.valueOf(typhoonID_lbl.getText()));
                add.setString(2, aIDc.getSelectedItem().toString());
                
                
                Statement ex = con.createStatement();
                String selectQuery1 = "SELECT * FROM typhoon WHERE TyphoonID="+typhoonID_lbl.getText()+"";
                System.out.println(selectQuery1);
                ResultSet rs2 = ex.executeQuery(selectQuery1);
                if(rs2.next()==false){
                    JOptionPane.showMessageDialog(this, "Typhoon ID "+typhoonID_lbl.getText()+" does not exist!"+"\nPlease refer to step 1");
                }else{
                Statement dup = con.createStatement();
                String selectQuery = "SELECT * FROM affected WHERE Typhoon_No="+typhoonID_lbl.getText()+" AND Area_ID='"+aIDc.getSelectedItem().toString()+"'";
                System.out.println(selectQuery);
                ResultSet rs = dup.executeQuery(selectQuery);
                 if (rs.next()==true){
                JOptionPane.showMessageDialog(this, "Area ID '"+aIDc.getSelectedItem().toString()+"' already exists in Typhoon ID "+typhoonID_lbl.getText()+"");
            }else{
                int id = Integer.parseInt(typhoonID_lbl.getText());
          try {
                int setInt = Integer.valueOf(typhoonID_lbl.getText());
                String areaID = aIDc.getSelectedItem().toString();
                
                typhoonID_lbl.setText(Integer.toString(id));
                
                Object[] obj = {setInt, areaID};
                model = (DefaultTableModel) affected_tbl.getModel();
                
                model.addRow(obj);
     
        } catch (Exception e) {
            e.printStackTrace();

        }
                int row = add.executeUpdate();
                 }
                    
           } 
          } catch (Exception e) {
            e.printStackTrace();

        }
              
        
    }//GEN-LAST:event_view2MouseClicked

    private void view2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_view2ActionPerformed

    private void aIDcItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_aIDcItemStateChanged

    }//GEN-LAST:event_aIDcItemStateChanged

    private void view3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view3MouseClicked
        get_ID();
    }//GEN-LAST:event_view3MouseClicked

    private void view3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view3ActionPerformed

    }//GEN-LAST:event_view3ActionPerformed

    private void view4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view4ActionPerformed
       JFileChooser fileChooser = new JFileChooser();
       FileNameExtensionFilter fnwf = new FileNameExtensionFilter("PNG JPG AND JPEG","png","jpeg","jpg");
       fileChooser.addChoosableFileFilter(fnwf);
       int load = fileChooser.showOpenDialog(null);
       
       if(load==fileChooser.APPROVE_OPTION){
           f = fileChooser.getSelectedFile();
           path = f.getAbsolutePath();
           imagePath.setText(path);
           ImageIcon ii = new ImageIcon(path);
           Image img = ii.getImage().getScaledInstance(570, 380, Image.SCALE_SMOOTH);
           imageLBL.setIcon(new ImageIcon(img));
       }
    }//GEN-LAST:event_view4ActionPerformed

    private void view1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view1ActionPerformed
        System.out.print("Image Path - "+ path);
        System.out.print("Image Name - "+ f.getName());
        File f = new File(path);
        
        
        
        try {
            InputStream is = new FileInputStream(f);
            Connection con = DBConnection.getConnection();
            Statement st2 = con.createStatement();
            PreparedStatement add = con.prepareStatement("insert into image_tbl values(?,?,?,?,?)");
                add.setInt(1, Integer.valueOf(typhoonID_lbl.getText()));
                add.setInt(2, Integer.valueOf(typhoonID_lbl.getText()));
                add.setString(3, f.getName());
                add.setString(4, path);
                add.setBlob(5, is);
                
                Statement ex = con.createStatement();
                String selectQuery1 = "SELECT * FROM typhoon WHERE TyphoonID="+typhoonID_lbl.getText()+"";
                System.out.println(selectQuery1);
                ResultSet rs2 = ex.executeQuery(selectQuery1);
                if(rs2.next()==false){
                    JOptionPane.showMessageDialog(this, "Typhoon ID "+typhoonID_lbl.getText()+" does not exist!"+"\nPlease refer to step 1");
                }else{
                
                int inserted = add.executeUpdate();
                
                if(inserted > 0){
                    JOptionPane.showMessageDialog(this, "Image Successfully added!");
                }
                }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AddRecord.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddRecord.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_view1ActionPerformed

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        new testTables().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        new ManageRecords().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel14MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        new AddRecord().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        new addAreas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel13MouseClicked

    private void typhoonID_lblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typhoonID_lblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typhoonID_lblActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aIDc;
    private rojeru_san.complementos.RSTableMetro affected_tbl;
    private javax.swing.JLabel close;
    private com.toedter.calendar.JDateChooser dDiss;
    private com.toedter.calendar.JDateChooser dFormed;
    private com.toedter.calendar.JDateChooser entPH;
    private javax.swing.JTextField hWind;
    private javax.swing.JLabel imageLBL;
    private javax.swing.JTextField imagePath;
    private javax.swing.JTextField intName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField lName;
    private javax.swing.JTextField lPressure;
    private com.toedter.calendar.JDateChooser leftPH;
    private javax.swing.JComboBox<String> signo;
    private javax.swing.JTextField totdmg;
    private javax.swing.JTextField totfat;
    private javax.swing.JTextField typhoonID_lbl;
    private javax.swing.JButton view;
    private javax.swing.JButton view1;
    private javax.swing.JButton view2;
    private javax.swing.JButton view3;
    private javax.swing.JButton view4;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
