/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pmora
 */
public class testTables extends javax.swing.JFrame {

    /**
     * Creates new form retired_typhoon
     */
    public testTables() {
        initComponents();
        defRec();
        combo();
        

    }
        DefaultTableModel model;
 
     public void defRec(){
         Connection con = DBConnection.getConnection();
        try{
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT year, SUM(Total_Damage) as sumdmg, SUM(Total_Fatal) as sumtot, category\n" +
"	  FROM typhoon as a, signal_cat as b\n" +
"      WHERE a.SignalNumber = "+1+" AND a.SignalNumber = b.signal_no\n" +
"    	  GROUP BY 1 HAVING  sumdmg > 0 AND sumtot > 0");
             DecimalFormat df = new DecimalFormat("$#,##0;(#,##0)"); 
             DecimalFormat ff = new DecimalFormat("#,##0;(#,##0)"); 
            while (rs.next()) {
               
               int year = rs.getInt("year");
               String sdmg = df.format(rs.getDouble("sumdmg"));
               String stot = ff.format(rs.getDouble("sumtot"));
               String ct = rs.getString("category");
               
                Object[] obj = {year, sdmg, stot, ct};
                model = (DefaultTableModel) sum1.getModel();
                model.addRow(obj);
                
                
            }  
            
        }catch(Exception e){
            e.printStackTrace();
        }
     }
     
     public void combo(){
         Connection con = DBConnection.getConnection();
         try{
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT TyphoonID from typhoon");
             DecimalFormat df = new DecimalFormat("$#,##0;(#,##0)"); 
             DecimalFormat ff = new DecimalFormat("#,##0;(#,##0)"); 
            while (rs.next()) {
               
              
               
               while (rs.next()) {
                String dd = rs.getString("TyphoonID");;
               jComboBox1.addItem(dd);
            }  
                
                
            }  
            
        }catch(Exception e){
            e.printStackTrace();
        }
     }
     
 
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        arID = new javax.swing.JLabel();
        view2 = new javax.swing.JButton();
        cat = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        sum1 = new rojeru_san.complementos.RSTableMetro();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        materialButton6 = new necesario.MaterialButton();
        materialButton3 = new necesario.MaterialButton();
        materialButton7 = new necesario.MaterialButton();
        materialButton5 = new necesario.MaterialButton();
        materialButton4 = new necesario.MaterialButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(234, 234, 234));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));
        jPanel1.setForeground(new java.awt.Color(249, 249, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(203, 203, 203));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Features");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 56, 117, 31));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Overview");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 93, 232, 37));

        jPanel10.setBackground(new java.awt.Color(203, 203, 203));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("Add Records");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 232, 37));

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Record Viewing");
        jPanel11.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 232, 37));

        jPanel14.setBackground(new java.awt.Color(203, 203, 203));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Manage Records");
        jPanel14.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        jPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 232, 37));

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText("Create Areas");
        jPanel12.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 232, 37));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));

        arID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        arID.setText("    ");
        jPanel4.add(arID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 647, 40, 30));

        view2.setText("Search");
        view2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view2MouseClicked(evt);
            }
        });
        view2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view2ActionPerformed(evt);
            }
        });
        jPanel4.add(view2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 430, 93, -1));

        cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jPanel4.add(cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, 121, -1));

        jLabel4.setText("Select Category Number:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 150, 20));

        sum1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Year", "Overall Damage", "Overall Fatality", "Category"
            }
        ));
        sum1.setColorBackgoundHead(new java.awt.Color(255, 255, 255));
        sum1.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        sum1.setColorBordeHead(new java.awt.Color(204, 204, 204));
        sum1.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        sum1.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        sum1.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        sum1.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        sum1.setColorSelBackgound(new java.awt.Color(0, 0, 0));
        sum1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sum1.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sum1.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sum1.setFuenteHead(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sum1.setGridColor(new java.awt.Color(204, 204, 204));
        sum1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sum1MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(sum1);
        if (sum1.getColumnModel().getColumnCount() > 0) {
            sum1.getColumnModel().getColumn(3).setHeaderValue("Category");
        }

        jPanel4.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 700, 300));

        jLabel6.setText("5 - Super Typhoon");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, -1, 24));

        jLabel8.setText("Displays the total damage and fatalities per year based on the user's typhoon signal selected input.");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, 24));

        jLabel12.setText("GUIDE:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, 24));

        jLabel13.setText("1 - Tropical Depression");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, -1, 24));

        jLabel20.setText("2 - Tropical Storm");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, 24));

        jLabel21.setText("3 - Severe Tropical Storm");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, -1, 24));

        jLabel22.setText("4 - Typhoon");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, -1, 24));

        materialButton6.setText("5");
        materialButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                materialButton6MouseClicked(evt);
            }
        });
        materialButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(materialButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 90, 30));

        materialButton3.setText("4");
        materialButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                materialButton3MouseClicked(evt);
            }
        });
        materialButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(materialButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 90, 30));

        materialButton7.setText("3");
        materialButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                materialButton7MouseClicked(evt);
            }
        });
        materialButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(materialButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 90, 30));

        materialButton5.setText("2");
        materialButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                materialButton5MouseClicked(evt);
            }
        });
        materialButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(materialButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 90, 30));

        materialButton4.setBackground(new java.awt.Color(204, 204, 204));
        materialButton4.setText("1");
        materialButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(materialButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 90, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 250, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1000, 610));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Typhoon Database System");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("iPhoon");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 1000, 660));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/im_project/lights.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 7, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/im_project/redo.png"))); // NOI18N
        jLabel10.setToolTipText("");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 0, -1, 28));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/im_project/mini logo.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/im_project/back.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 0, -1, 28));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/im_project/User-Interface-Delete-Sign-icon.png"))); // NOI18N
        close.setToolTipText("");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, -1, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void view2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_view2ActionPerformed

    private void view2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view2MouseClicked
        Connection con = DBConnection.getConnection();
        try{
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT year, SUM(Total_Damage) as sumdmg, SUM(Total_Fatal) as sumtot, category\n" +
"	  FROM typhoon as a, signal_cat as b\n" +
"      WHERE a.SignalNumber = "+cat.getSelectedItem().toString()+" AND a.SignalNumber = b.signal_no\n" +
"    	  GROUP BY 1 HAVING  sumdmg > 0 OR sumtot > 0");
             DecimalFormat df = new DecimalFormat("$#,##0;(#,##0)"); 
             DecimalFormat ff = new DecimalFormat("#,##0;(#,##0)"); 
             model.setRowCount(0);      
            while (rs.next()) {
               
               int year = rs.getInt("year");
               String sdmg = df.format(rs.getDouble("sumdmg"));
               String stot = ff.format(rs.getDouble("sumtot"));
               String ct = rs.getString("category");
               
               
                Object[] obj = {year, sdmg, stot, ct};
                model = (DefaultTableModel) sum1.getModel();
                
                model.addRow(obj);
                
                
            }  
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_view2MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        new ManageRecords().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        new AddRecord().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
         new ManageRecords().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel14MouseClicked

    private void sum1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sum1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sum1MouseClicked

    private void materialButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialButton6ActionPerformed

    private void materialButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialButton3ActionPerformed

    private void materialButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialButton7ActionPerformed

    private void materialButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialButton5ActionPerformed

    private void materialButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialButton4ActionPerformed

    private void materialButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialButton5MouseClicked
        new testTables1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_materialButton5MouseClicked

    private void materialButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialButton7MouseClicked
        new testTables2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_materialButton7MouseClicked

    private void materialButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialButton3MouseClicked
        new testTables3().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_materialButton3MouseClicked

    private void materialButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialButton6MouseClicked
       new testTables4().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_materialButton6MouseClicked

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        new addAreas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testTables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testTables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testTables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testTables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testTables().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arID;
    private javax.swing.JComboBox<String> cat;
    private javax.swing.JLabel close;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane8;
    private necesario.MaterialButton materialButton3;
    private necesario.MaterialButton materialButton4;
    private necesario.MaterialButton materialButton5;
    private necesario.MaterialButton materialButton6;
    private necesario.MaterialButton materialButton7;
    private rojeru_san.complementos.RSTableMetro sum1;
    private javax.swing.JButton view2;
    // End of variables declaration//GEN-END:variables
}
